package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public M setPostlocation(java.lang.String postlocation) {
		set("postlocation", postlocation);
		return (M)this;
	}

	public java.lang.String getPostlocation() {
		return get("postlocation");
	}

	public M setVisibility(java.lang.Integer visibility) {
		set("visibility", visibility);
		return (M)this;
	}

	public java.lang.Integer getVisibility() {
		return get("visibility");
	}

	public M setUsrid(java.lang.Integer usrid) {
		set("usrid", usrid);
		return (M)this;
	}

	public java.lang.Integer getUsrid() {
		return get("usrid");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
		return (M)this;
	}

	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public M setDiscard(java.lang.Integer discard) {
		set("discard", discard);
		return (M)this;
	}

	public java.lang.Integer getDiscard() {
		return get("discard");
	}

}
