package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseImage<M extends BaseImage<M>> extends Model<M> implements IBean {

	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}

	public java.lang.String getPath() {
		return get("path");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return get("type");
	}

	public M setIdx(java.lang.Integer idx) {
		set("idx", idx);
		return (M)this;
	}

	public java.lang.Integer getIdx() {
		return get("idx");
	}

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setBlogid(java.lang.Integer blogid) {
		set("blogid", blogid);
		return (M)this;
	}

	public java.lang.Integer getBlogid() {
		return get("blogid");
	}

}
