package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public M setPostlocation(java.lang.String postlocation) {
		set("postlocation", postlocation);
		return (M)this;
	}

	public java.lang.String getPostlocation() {
		return get("postlocation");
	}

	public M setVisibility(java.lang.Integer visibility) {
		set("visibility", visibility);
		return (M)this;
	}

	public java.lang.Integer getVisibility() {
		return get("visibility");
	}

	public M setUsrid(java.lang.Integer usrid) {
		set("usrid", usrid);
		return (M)this;
	}

	public java.lang.Integer getUsrid() {
		return get("usrid");
	}

	public M setUsrname(java.lang.String usrname) {
		set("usrname", usrname);
		return (M)this;
	}

	public java.lang.String getUsrname() {
		return get("usrname");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}

	public java.util.Date getTime() {
		return get("time");
	}

}
