-- MySQL Script generated by MySQL Workbench
-- Wed Mar 22 17:07:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jfinal_wz369
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jfinal_wz369
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jfinal_wz369` DEFAULT CHARACTER SET utf8 ;
USE `jfinal_wz369` ;

-- -----------------------------------------------------
-- Table `jfinal_wz369`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfinal_wz369`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NULL,
  `password` VARCHAR(50) NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  `nickname` VARCHAR(50) NULL,
  `iconurl` VARCHAR(50) NULL,
  `qq` VARCHAR(20) NULL,
  `weixin` VARCHAR(20) NULL,
  `weibo` VARCHAR(50) NULL,
  `district` VARCHAR(50) NULL,
  `createtime` DATETIME NULL,
  `updatetime` DATETIME NULL,
  `discard` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iduser_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jfinal_wz369`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfinal_wz369`.`session` (
  `id` INT NOT NULL,
  `session` VARCHAR(45) NULL,
  `userid` INT NULL,
  `createtime` DATETIME NULL,
  `expiretime` DATETIME NULL,
  `oauthtype` VARCHAR(10) NULL,
  `active` TINYINT NULL,
  `updatetime` DATETIME NULL,
  `discard` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `userid_idx` (`userid` ASC),
  CONSTRAINT `userid`
    FOREIGN KEY (`userid`)
    REFERENCES `jfinal_wz369`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jfinal_wz369`.`userinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfinal_wz369`.`userinfo` (
  `id` INT NOT NULL,
  `userinfo` VARCHAR(200) NULL,
  `oauthtype` VARCHAR(10) NULL,
  `sessionid` INT NULL,
  `userid` INT NULL,
  `createtime` DATETIME NULL,
  `updatetime` DATETIME NULL,
  `discard` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `sessionid_idx` (`sessionid` ASC),
  INDEX `userid_idx` (`userid` ASC),
  CONSTRAINT `sessionid`
    FOREIGN KEY (`sessionid`)
    REFERENCES `jfinal_wz369`.`session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userid`
    FOREIGN KEY (`userid`)
    REFERENCES `jfinal_wz369`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

