package com.my24d.caixun.common.model;

import com.my24d.caixun.common.model.base.BaseSession;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Session extends BaseSession<Session> {
	public static final Session dao = new Session().dao();
}
