package com.my24d.caixun.common.model;

import com.my24d.caixun.common.model.base.BaseUserinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userinfo extends BaseUserinfo<Userinfo> {
	public static final Userinfo dao = new Userinfo().dao();
}
