package com.demo.common.model;

import com.demo.common.model.base.BaseImage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Image extends BaseImage<Image> {
	public static final Image dao = new Image().dao();
}
